services:
  mysql:
    image: mysql:5.7
    env_file:
      - ./docker/env/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci


volumes:
  mysql-data: